name: test

x-env: &default-env
  POSTGRES_USER: "osm_user"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD: "test_db_pass"
  POSTGRES_DB: "osm"

services:
  db:
    image: "postgis/postgis:18-3.6"
    environment:
      <<: *default-env
    volumes:
      - ./postgis/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  test:
    build:
      dockerfile: Dockerfile
      args:
        TESTS: "true"
    environment:
      <<: *default-env
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./data:/data
      - ./tests:/tests
