name: QA

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements/requirements-dev.txt

      - name: Quality check – format
        if: success() || failure()
        run: python3 -m ruff format --diff .

      - name: Quality check – lint
        if: success() || failure()
        run: python3 -m ruff check --diff .
